from PyQt5.QtGui import QPen, QBrush, QColor

NODE_BORDER_DEFAULT_PEN = QPen(QColor("#000"))

NODE_ORANGE_FILL_BRUSH = QBrush(QColor("#FC5531"))
NODE_FILL_DEFAULT_BRUSH = NODE_ORANGE_FILL_BRUSH

NODE_VERTICAL_SPACING = 100
NODE_HORIZONTAL_SPACING = 100